[colors.primary]
background = '#101417'
foreground = '#dfe3e8'
 
[colors.cursor]
text = '#dfe3e8'
cursor = '#c1c7ce' 
 
[colors.vi_mode_cursor]
text = '#101417'
cursor = '#94cdf7' 
 
[colors.search.matches]
foreground = '#41474d' 
background = '#cec0e8' 
 
[colors.search.focused_match]
foreground = '#41474d' 
background = '#94cdf7' 
 
[colors.footer_bar]
foreground = '#41474d' 
background = '#dfe3e8' 
 
[colors.hints.start]
foreground = '#41474d' 
background = '#b7c9d9' 
 
[colors.hints.end]
foreground = '#41474d' 
background = '#b7c9d9' 
 
[colors.selection]
text = '#101417'
background = '#94cdf7'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#94cdf7' 
yellow = '#246488' 
blue = '#94cdf7' 
magenta = '#cec0e8' 
cyan = '#b7c9d9' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
