[config]
reload_apps = true
set_wallpaper = true
wallpaper_tool = "Swww"
swww_options = [
    "--transition-fps",
    "72",
    "--transition-type",
    "wipe",
    "--transition-duration",
    "1",
]

[config.reload_apps_list]
gtk_theme = true
alacritty = true

[templates]
hyprland = { input_path = '~/.config/matugen/templates/hyprland.conf', output_path = '~/.cache/matugen/compiled/hyprland.conf' }
qtct = { input_path = '~/.config/matugen/templates/qtct.conf', output_path = '~/.cache/matugen/compiled/qt.conf' }
alacritty = { input_path = '~/.config/matugen/templates/alacritty.toml', output_path = '~/.cache/matugen/compiled/alacritty.toml' }
css = { input_path = '~/.config/matugen/templates/colors.css', output_path = '~/.cache/matugen/compiled/colors.css' }
sass = { input_path = '~/.config/matugen/templates/colors.scss', output_path = '~/.cache/matugen/compiled/colors.scss' }
gradience = { input_path = '~/.config/matugen/templates/gradience.json', output_path = '~/.cache/matugen/compiled/gradience.json' }
lua = { input_path = '~/.config/matugen/templates/colors.lua', output_path = '~/.cache/matugen/compiled/colors.lua' }
