[colors.primary]
background = '#11140f'
foreground = '#e1e4da'
 
[colors.cursor]
text = '#e1e4da'
cursor = '#c3c8bc' 
 
[colors.vi_mode_cursor]
text = '#11140f'
cursor = '#a5d395' 
 
[colors.search.matches]
foreground = '#43483f' 
background = '#a0cfd2' 
 
[colors.search.focused_match]
foreground = '#43483f' 
background = '#a5d395' 
 
[colors.footer_bar]
foreground = '#43483f' 
background = '#e1e4da' 
 
[colors.hints.start]
foreground = '#43483f' 
background = '#bbcbb2' 
 
[colors.hints.end]
foreground = '#43483f' 
background = '#bbcbb2' 
 
[colors.selection]
text = '#11140f'
background = '#a5d395'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#a5d395' 
yellow = '#406836' 
blue = '#a5d395' 
magenta = '#a0cfd2' 
cyan = '#bbcbb2' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
