# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=HDMI-A-1, 1920x1080@60, 0x0, 1


# See https://wiki.hyprland.org/Configuring/Keywords/ for more



# Source a file (multi-file configs)
source = ~/.cache/wal/colors-hyprland.conf

# Set programs that you use
$terminal = alacritty
$fileManager = thunar
$menu = rofi
$browser = chromium
$text = subl
$code = vscodium
$record = obs

source = ~/.config/hypr/environment/unk0wn.conf
source = ~/.config/hypr/animations/rusty.conf
source = ~/.config/hypr/devices/unk0wn.conf
source = ~/.config/hypr/decorations/rusty.conf
source = ~/.config/hypr/exec/unk0wn.conf
source = ~/.config/hypr/keybinds/unk0wn.conf
source = ~/.config/hypr/windowmanagers/unk0wn.conf
source = ~/.config/hypr/windowrules/unk0wn.conf
source = ~/.config/hypr/input/unk0wn.conf
source = ~/.config/hypr/general/unk0wn.conf


gestures {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    workspace_swipe = off
}

misc {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    force_default_wallpaper = -1 # Set to 0 or 1 to disable the anime mascot wallpapers
}

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#executing for more
device:epic-mouse-v1 {
    sensitivity = -0.5
}


