windowrule = float,^(pavucontrol)$
windowrule = float,^(blueman-manager)$
windowrule = tile,^(nm-connection-editor)$
windowrule = tile,^(nm-applet)$
windowrule = tile,^(blueman-applet)$
windowrulev2 = nomaximizerequest, class:.*

windowrule = float,^(kitty)$
windowrule = move 100 15,^(kitty)$
windowrule = size 94% 60,^(kitty)$
windowrule = stayfocused , ^(kitty)$